# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1d\n\nMsgRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x19\n\x08MsgReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8e\x01\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12\x43\n\rSayHelloAgain\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x32\x45\n\x08Minitalk\x12\x39\n\x07SendMsg\x12\x16.helloworld.MsgRequest\x1a\x14.helloworld.MsgReply\"\x00\x42\x0fZ\r./server/mainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./server/main'
  _globals['_MSGREQUEST']._serialized_start=32
  _globals['_MSGREQUEST']._serialized_end=61
  _globals['_MSGREPLY']._serialized_start=63
  _globals['_MSGREPLY']._serialized_end=88
  _globals['_HELLOREQUEST']._serialized_start=90
  _globals['_HELLOREQUEST']._serialized_end=118
  _globals['_HELLOREPLY']._serialized_start=120
  _globals['_HELLOREPLY']._serialized_end=149
  _globals['_GREETER']._serialized_start=152
  _globals['_GREETER']._serialized_end=294
  _globals['_MINITALK']._serialized_start=296
  _globals['_MINITALK']._serialized_end=365
# @@protoc_insertion_point(module_scope)
