# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minitalk.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eminitalk.proto\x12\x08minitalk\"\x1d\n\nMsgRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x19\n\x08MsgReply\x12\r\n\x05reply\x18\x01 \x01(\t2A\n\x08Minitalk\x12\x35\n\x07SendMsg\x12\x14.minitalk.MsgRequest\x1a\x12.minitalk.MsgReply\"\x00\x42\x0fZ\r./server/mainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitalk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./server/main'
  _globals['_MSGREQUEST']._serialized_start=28
  _globals['_MSGREQUEST']._serialized_end=57
  _globals['_MSGREPLY']._serialized_start=59
  _globals['_MSGREPLY']._serialized_end=84
  _globals['_MINITALK']._serialized_start=86
  _globals['_MINITALK']._serialized_end=151
# @@protoc_insertion_point(module_scope)
